name: Major P
favicon: null
layout_spectrum: 0.7622
typography_spectrum: 0.3858093249145895
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fafbea'
    - '#090405'
    - '#bb1737'
    - '#407f40'
    - '#c4a350'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
